### PR TITLE
Add ANALOG_WRITE to FastIO headers

### PR DESCRIPTION
**Pull request by thinkyhead**
Placeholders for analog write, so we can scale it for platforms that use a 16-bit range.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Looks like these will be needed, after all…
image

**Comment by thinkyhead** [comment]
…of course, I'm thinking `((duty + 1) << 8) + 1`…

**Comment by pinchies** [comment]
Looking at the source code, I think that it was required with the maple library, but is no longer required with the updated library from Roger that we are using.

**Comment by thinkyhead** [comment]
Ok, I've reverted that change. To keep all this straight —and not just for me— I will need to sort out what platform code we're using for each of the HALs and document that in comments clearly in a `README.md` in each HAL folder.

**Comment by pinchies** [comment]
Sounds good. To be crystal clear - the current two options for STM32F1 are the[ community created library maintained by Roger,](https://github.com/rogerclarkmelbourne/Arduino_STM32) which is a descendant of the LeafLabs maple libraries with some changes, while the other option is the[ official library that is provided by ST](https://github.com/stm32duino). I'm using the library from Roger at the moment.

**Comment by thinkyhead** [comment]
> Perhaps the comments could go in there, as a thought?

Yes, best to have documentation where it can be discovered!

**Pull request merged**
